FROM frappe/erpnext-worker:v14.0.3

USER root
RUN apt update && apt -y install git && apt clean

WORKDIR /home/frappe/frappe-bench/apps
#RUN --mount=type=cache,target=/root/.cache/pip git clone -b v13 https://github.com/libracore/erpnextswiss.git && install-app erpnextswiss
RUN --mount=type=cache,target=/root/.cache/pip git clone https://github.com/tarioch/tariocherp.git && install-app tariocherp

WORKDIR /home/frappe/frappe-bench/sites
USER frappe
