name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: "docker-erpnext"
      - name: Set env variable APPS_JSON_BASE64
        run: |
          echo "APPS_JSON_BASE64=$(base64 --wrap=0 docker-erpnext/apps.json)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          repository: frappe/frappe_docker
          path: "frappe_docker"
      - name: Publish Snapshot to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: "!contains(github.ref, 'refs/tags/v') && !contains(github.ref, 'refs/pull')"
        with:
          name: tarioch/erpnext
          workdir: frappe_docker
          dockerfile: images/custom/Containerfile
          buildargs: APPS_JSON_BASE64
          snapshot: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Release to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: tarioch/erpnext
          dockerfile: Dockerfile
          tagging: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
