name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish Snapshot to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: "!contains(github.ref, 'refs/tags/v') && !contains(github.ref, 'refs/pull')"
        with:
          name: tarioch/erpnext-worker
          snapshot: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Release to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        if: contains(github.ref, 'refs/tags/v')
        with:
          name: tarioch/erpnext-worker
          tagging: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
